version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: skillscan-db
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  skillscan-app:
    build: .
    container_name: skillscan-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
